import React, { useEffect, useState } from "react";
import { Amplify } from "aws-amplify";
import { generateClient } from "aws-amplify/api";
import { ResponsiveBar } from "@nivo/bar";
import config from './aws-exports-amplify.js';

// GraphQL helpers generated by Amplify codegen
import { processTask } from './graphql/mutations';
import { listDefects } from './graphql/queries';

// config amplify
Amplify.configure(config);
const Client = generateClient();

function App() {
    const [data, setData] = useState([]);
    const [summary, setSummary] = useState(""); 
    // loads init data
    useEffect(() => {
        fetchInitialData();
    }, []);

// flattens nested data
    const fetchInitialData = async () => {
        try {
            const response = await Client.graphql({ query: listDefects });
            const rawData = response.data.listDefects;

            const flattened = rawData.map(item => ({
                machine: item.molding_machine_id,
                rejectCount: item.object_detection?.reject ? 1 : 0,
                severity: item.object_detection?.contamination_defect?.pixel_severity?.value || 0
            }));

            setData(flattened);
            setSummary("Initial data view loaded from DocumentDB.");
        } catch (error) {
            console.error("Unable to fetch current defects list:", error);
            setSummary("Error: Could not load data.");
        }
    };

//triggers autogen task
    const fetchAgentTask = async (userPrompt) => {
        try {
            const response = await Client.graphql({
                query: processTask, 
                variables: {
                    task: userPrompt,
                    sessionId: "user-session-123"
                }
            });

            const { summary: agentSummary, nivoData } = response.data.processTask;

            setSummary(agentSummary);
            
            // parse JSON- chaining method to prevent crashses if DocumentDB has missing fields
            const parsedData = typeof nivoData === "string" ? JSON.parse(nivoData) : nivoData;
            setData(parsedData);

        } catch (error) {
            console.error("Unable to fetch agent analysis:", error);
            setSummary("Error: AI Agent was unable to process your request, contact Admin for more details.");
        }
    };

    return (
        <div style={{ height: "700px", width: "100%", padding: "20px", fontFamily: "sans-serif" }}>
            <h2>Defects Analytics Dashboard</h2>
            
            {/* Summary Message from the AI Agent */}
            <p style={{ 
                fontStyle: "italic", 
                backgroundColor: "#f4f4f4", 
                padding: "10px", 
                borderRadius: "5px" 
            }}>
                {summary || "Connecting to AppSync..."}
            </p>

            {/* User Customization Controls */}
            <div style={{ marginBottom: "20px" }}>
                <button onClick={() => fetchInitialData()}>Reset View</button>
                <button 
                    style={{ marginLeft: "10px" }}
                    onClick={() => fetchAgentTask("Show me machine data with high severity")}
                >
                    Run AI Analysis
                </button>
            </div>

            {/* Chart plots */}
            {data.length > 0 ? (
                <div style={{ height: "500px" }}>
                    <ResponsiveBar
                        data={data}
                        keys={['rejectCount', 'severity']}
                        indexBy="machine"
                        margin={{ top: 50, right: 130, bottom: 50, left: 60 }}
                        padding={0.3}
                        valueScale={{ type: "linear" }}
                        colors= {{ scheme: "nivo" }}
                        axisBottom={{
                            legend: "Machine ID",
                            legendPosition: "middle",
                            legendOffset: 40
                        }}
                        axisLeft={{
                            legend: "Count / Severity",
                            legendPosition: "middle",
                            legendOffset: -50
                        }}
                    />
                </div>
            ) : (
                <p>Retrieving data from database...</p>
            )}
        </div>
    );
}

export default App;
